### ISSUE TITLE
ModuleNotFoundError: No module named 'monaistream.util'

### ISSUE THREAD

**Issue by qin53027** [Project-MONAI/MONAIStream#60]
Hi,

Today I did : git clone https://github.com/Project-MONAI/MONAIStream and followed by : ./start_devel.sh

Then inside the docker shell, I issued the following command to change my torch model into the TRT engine model:

monaistream convert -i 4light_test_ep4.pt -o monai_unet.engine -I INPUT__0 -O OUTPUT__0 -S 1 3 800 80

But I got following error: ModuleNotFoundError: No module named 'monaistream.util'

Can you please let me how to solve this problem?

Thanks
Jimmy

**Comment by aihsani** [comment]
Looking into this

**Comment by aihsani** [comment]
I've put in a fix https://github.com/Project-MONAI/MONAIStream/pull/61. Once this fix is merged please retry with the main branch

Sorry for the delay but somehow I never got the notification for this bug
